### ISSUE TITLE
Feature request: allow admin to modify maximum connections

### ISSUE THREAD

**Issue by CoreyBurger** [nextcloud/documentserver_community#31] opened 2020-01-22 17:26 UTC
The last issue was closed without discussion, so reopening a new issue. The 20 connection limit makes no sense and is contrary to the spirit of open source. While I understand that more connections need more computing power, the better solution is to the following:

1. Publish a guide showing limits of connections based on hardware
2. Make those limits configurable within the UI

**Comment by jospoortvliet** [comment] 2020-01-22 19:59
Hi Corey,

The community document server is meant for private use. It has a variety of fundamental limitations that will cause issues when used at scale. Together with ONLYOFFICE we decided to put in this limit (the same as in the ONLYOFFICE community docker image) to avoid a bad experience.

If you need more than 20 connections, you can easily contact us and get the enterprise version, which will be much faster and nicer in use for your users. And of course, you help the further development of the product and get top-notch support.

If you really don't want to pay us for our work, that is of course fine, the source is open. You can rebuild the whole thing without the limitation, if your hardware can handle it and your users are willing to wait. Our license allows that. But we will not be facilitating something that can give people a bad impression of onlyoffice or our product.

>  is contrary to the spirit of open source.
Just to reply to that: the spirit of open source is collaboration and contribution. It is not "making it easier for business users to not contribute anything to open source". Nextcloud would be better software if all commercial organizations would pay us to improve it further. We could build in limits in Nextcloud that would certainly result in more companies paying us - and thus a better product for everyone. We don't do that, because we don't really like it - but it would, strictly speaking, be just as much "in the spirit of open source" as anything, if not more: anyone still can access and modify the code, contribute and so on. We'd just be able to make a better product with more funds.

Nextcloud is doing just fine without putting more pressure on companies to pay, but certainly lots of open source businesses have failed, and lots of open source contributors get yelled at on github by people who don't want to pay them for their work - there is certainly an issue in open source, in that regard. But the issue is NOT that the developers don't work enough for free, rather the opposite. I'd be happy to discuss this over a beer at FOSDEM...

**Comment by CoreyBurger** [comment] 2020-01-22 20:05
The enterprise edition requires things I don't have (a VPS or non-shared server). But I do have access to a fairly powerful server. I am going to patch out the restriction in our live server, but would rather not carry the delta.

Given the reply, I am assuming you would not accept a patch to do the above. Given it is open source, if I forked it and submitted a 'UsualOffice' community server as an app, would NextCloud accept that?

**Comment by SimonMGS** [comment] 2020-01-23 00:50
> The community document server is meant for private use. It has a variety of fundamental limitations that will cause issues when used at scale. Together with ONLYOFFICE we decided to put in this limit (the same as in the ONLYOFFICE community docker image) to avoid a bad experience.

>If you need more than 20 connections, you can easily contact us and get the enterprise version, which will be much faster and nicer in use for your users

According to this [article posted by Autoize](https://autoize.com/building-onlyoffice-document-server-from-source/), "the paid version of their software is identical to the open source version running in single node mode", and "a server with 4 GB of RAM and 4 CPU cores can easily support 200 to 400 concurrent users."

So, I'm sorry, but I suspect that what you're telling us about the technical necessity of the 20 connection limit is simply untrue.

**Comment by jospoortvliet** [comment] 2020-01-24 17:14
Hi @SimonMGS,

I understand you are skeptical, but please understand that the version that is described in the article by Autoize is not the same as what we ship in our app store. We have rewritten a part o the back-end of ONLYOFFICE into PHP, which makes it possible to install it with one click (no need for packages or docker images) but it does get considerably slower. Now indeed, we could remove the 20 connections limit, but our partner has requested we keep this in and I really feel we are under no obligation to make it easier for business users to run software for free. After all, open source is about freedom, not about not paying.

**Comment by CoreyBurger** [comment] 2020-01-24 17:39
Maybe don't shame people for not (yet) contributing (code). There are plenty of ways to make open source awesome without coding a single line. I say this as somebody who was involved with Ubuntu at relatively high levels for  years despite not being a coder at the time.

Here is my suggestion for a solution (and I am happy to dust off my rust PHP to make it happen):

Stage one:
1. Remove the hard cap
2. Create a variable in the backend that limits connections. By default that is set to 20
3. Write up some documentation about limits based on hardware

Stage two:
1. Expose that variable in the UI with a strong note about slowdowns after 20

As most people don't change defaults, this means that for most installs, the limit will still be 20. But if you have more hardware or can tolerate slow response, you can up it.

**Comment by SimonMGS** [comment] 2020-01-24 22:58
> Now indeed, we could remove the 20 connections limit, but our partner has requested we keep this in and I really feel we are under no obligation to make it easier for business users to run software for free. After all, open source is about freedom, not about not paying.
> 
> Edit: point is, I'd like to respect the author's wishes, in this case, ONLYOFFICE. Do we legally have to? No, but I don't legally have to be nice to other people either. I still think I should ;-) They did all the work, so they deserve some credit for that and a chance to run a business. After all, it isn't like you or others contribute to the ONLYOFFICE code base, right? So without business - there won't be a great office suite.

The key thing here is to be clear what the OnlyOffice model actually is. This is artificially limiting the software, to have an arbitrary level of functionality, beyond which they’ve decided we should pay.

That’s not the same as an effort to make software that’s as functional as possible, and then selling support and consulting for clustering and so on, when the natural limits are reached. Instead, this is deliberately restricting the functionality of the community version in favour of the proprietary version, which is the opencore model that Nextcloud has always explicitly rejected. OnlyOffice clearly uses that model, and now that Nextcloud has integrated its own implementation in their stack, you’ve adopted it too, for that part of the functionality.

You’re within your rights to do that, in terms of the GPL. But I think there’s two problems.

The first is with this attempt to portray deliberate software limitation as a necessity of the constraints of the software, when we both know that’s not the case. The OnlyOffice Community edition is as fundamentally functional as the enterprise version, but has an artificial 20 connection limit. I understand that the Nextcloud implementation is different, but it just happens to be so comparatively inefficient, that it requires the exact same limit? Come on now...

The second is that I don’t think Nextcloud can continue to claim it doesn’t embrace opencore, when it’s integrated and is cooperating with software that very clearly is, and making it an advertised part of the key functionality.

Just at FOSDEM 2018, [Frank discussed ](https://archive.fosdem.org/2018/schedule/event/nextcloud/)how restricting functionality to enterprise versions has a toxic effect on the community, and even that it’s fundamentally unsustainable. So the issue isn’t with whether it’s acceptable under the GPL, it’s a question which kind of opensource project Nextcloud is now.

**Comment by autoize** [comment] 2020-01-25 23:34
Agree that keeping the 20 connection limit, but exposing it as a variable that advanced users can change, accompanied by a notice that purchasing the enterprise edition _may_ result in better performance, would be a fair compromise as @CoreyBurger has described. 

The NextCloud GmbH team should be commended for the great work that they do, and based on the PR that they routinely put out, they have no shortage of enterprise users (including major governments) who happily pay for enterprise support plans that they offer. 

Whenever possible, we look for opportunities to support the core developers of the open source software that we deploy and integrate for our clients, by referring them to purchase an enterprise support subscription where it makes sense. 

But @CoreyBurger makes a good point here. NextCloud forked from OwnCloud because it wanted to avoid the "open core" model that OwnCloud insisted on moving towards by reserving certain features for the paid edition. 

Many contributors to the NextCloud project may not find crippling features (or bundling apps that cripple features) in alignment with the social contract that they originally agreed upon when they began contributing to the project.

**Comment by jospoortvliet** [comment] 2020-01-28 10:29
All,

I agree with pretty much all points made. We don't believe artificially limiting software is a good way forward. Though I personally find it :sob:  that it seemingly helps increase sales: people are willing to pay for the convenience of not having to rebuild/recompile the docker container, not for the support that a company offers.  This, as I said above, says more about how most people still just use Open Source not to have to pay than that it is about principle or ideal. And I personally feel little obligation to make the life of people who just care about not paying any easier.

In either case, we don't do this in our software. But we don't write ONLYOFFICE and we respect the people who DO the work. And those who do the work get to decide, I think it is disrespectful to make such changes without their agreement. We ship their app, the way they want. If you want to convince them to change their ways, please, discuss it with them. You can also take it up with Collabora, the same way - on their channels.

Btw @autoize please follow our trademark guidelines and don't use the Nextcloud logo or any of our screenshots on your website unless you're a partner. Talking of being honest about business model, how would you describe yours? Earning money by helping people not pay for their use of open source? That is exactly why many open source companies are shutting down or go open core or put in limitations in their code. Perhaps Simon and Corey and others should focus their effort on getting all companies that do this to instead become official partners and contribute fairly to the projects they earn their business with. So open source developers can earn a honest living and don't have to limit their software.

**Comment by SimonMGS** [comment] 2020-01-28 12:56
One of the things Frank covered in that talk, is how some companies use the term opensource purely for its marketing value. I think, if we’re suggesting that people ought to respect their wishes and not modify or distribute the software to remove the huge restriction, then we’re into that territory - what’s the point of it being notionally opensource in the first place? If that’s the intent, and we’re not supposed to change it, it might just as well be proprietary freemium software that grants limited functionality. 

It does come as a bit of a surprise to see opencore software shipping as part of Nextcloud Hub, when just in August 2019 the [Nextcloud values statement](https://help.nextcloud.com/t/the-nextcloud-mission-and-principles/58062) made it clear:

> Open Source
> Everything we do is 100% open source. We do not do open core or proprietary extensions.
> 

Yet now Nextcloud has done a deal to include exactly that in its default stack, and we’re being told how the proprietary version is “much nicer and faster”.

You can perhaps see that people might be concerned about this direction, without us all necessarily being a pack of entitled little monsters that don’t want workers to earn a living?

**Comment by jospoortvliet** [comment] 2020-01-28 14:41
So what IS your concern? There is still no line of non-opensource-code in our product.

**Comment by SimonMGS** [comment] 2020-01-28 16:11
The concern, and I don't think it's just mine, is essentially that by doing a deal to integrate OnlyOffice as part of the default functionality of Nextcloud Hub, you have in effect introduced the open core model via the side door, and are pushing users towards the much "faster and nicer" proprietary versions.

In relation to this particular github issue, you are rejecting the request for user-configurability of the hard limitation in the Nextcloud fork, in order to co-operate in feature restriction with your partners. 
To me, that seems at odds with rejecting the open core model as part of Nextcloud's values.

The larger concern is that this then calls into question Nextcloud's commitment not to embrace open core, going forward.

**Comment by jospoortvliet** [comment] 2020-01-30 10:06
Ok, understood. So similar arguments why people think we shouldn't be using Github, for example - yes, we chose to depend on/work with a party that isn't as 'pure' as we would like. That is indeed a risk.

But please don't take our promises out of context. We have committed to not doing an open core business model. Not to not work with anyone who does - the libraries Nextcloud builds on have all kinds of business models, too. We just look for license compatibility, the protection of our users is in the AGPL. We promised to not write proprietary code - but partners do, like our Outlook add-in partner, and even our official iOS client was fully proprietary for the first year or so, until we convinced our partner to open source it.

So if you feel this is a slipperly slope, well, we were already far further down that slope on the day we launched our company than that we are with ONLYOFFICE.

In the end, goal number 1 is to make the best possible Nextcloud for the largest number of private users. Business users are a means to an end, a way to pay for goal number 1. And our principles are what we believe is the best way to get there - but we won't force everyone in our ecosystem to go beyond complying with the license.

Things like keeping using twitter & Facebook to promote Nextcloud, using github, using dependencies that might not be LGPL but at least compatible licensed - yeah, that is because goal nr 1 is what we go after. Pragmatism.

Some open source companies do things like making it super hard to deploy the code without their help, or indeed put in limitations. It isn't nice, but if the end goal is to make a better product and it works - I have absolutely zero ideological issues with it. Just like I don't feel bad at all doing something that makes the life of our business users harder unless they pay in, as long as we keep the source open. At ownCloud, I never felt particularly bad about the way the open core model was done. I think it's a long term problem as it creates a pressure from sales to increase the 'closed' part, and it is a risk for customers, and not nice to community - but if it is only so that a tiny few apps are closed and the rest is open, it isn't too bad in practice. Half the web runs on that business model (NGINX anyone?). There is a difference between ideal and practical.

**Comment by jospoortvliet** [comment] 2020-01-30 10:22
On a different note, if you're worried about the future of Nextcloud - look at what Amazon has already done to a few open source projects. Companies that essentially 'compete' with the original project, by simply not contributing so they can be much cheaper, are a huge issue in open source. 

There is a lot of this in the LibreOffice community, from what I can tell - a race to the bottom. The less you actually contribute to LibreOffice, the cheaper services you can offer - so everybody has a big incentive to not contribute anymore. Of course it has downsides for the customer, they might not get what they expect.

If you get libreoffice 'support' from a random IT company, they can install it and answer basic questions (say level 1 and 2 support). But if there's a problem, they can't fix it like Collabora could. From them, you buy an insurance - that always pays out, be it a cold or cancer. From that random third party IT company, you would buy an insurance that only covers a cold. How can you know the difference? The random IT company has a good reason to confuse you, so Collabora created its own trademark to differentiate a bit. It is still barely enough - if this effect was not there, LibreOffice would be able to compete with Microsoft Office for sure. Easily.

We see the same in our ecosystem. Of course, we don't offer services to small companies, so loads of hosting and service providers take care of small customers, and that's great. But bigger ones are sometimes confused and think a company like autoize is the same as we are, and that's a problem in two ways. First, they pay for somebody who, when it really goes wrong, can only look on our forums for help. Like an insurance that only works when you're not really sick (or just have a broken Apache config). And second, money goes to a random IT company shareholder somewhere, not to Nextcloud development, so the whole community loses to that.

I can't tell you what exactly this means for Nextcloud. If big companies would only buy support from partners or us directly, would we be able to hire 25 more developers to join the 25 we have? 80? 150? Hard to say. But certainly I believe it's a bigger threat to the future of Nextcloud than our collaboration with ONLYOFFICE. And already holding is back quite a bit.

We have trademark guidelines that help a little, so if you see a company using our logo on their website but they are not on nextcloud.com/partners - say something to them. It is a violation of the rules and harmful to the community.

**Comment by autoize** [comment] 2020-02-04 12:57
It is not the inclusion of OnlyOffice in the app store, so much as the handling of the comms around it that makes one question whether NextCloud GmbH is acting in good faith. The shaming of community members as "freeloaders" by @jospoortvliet in this thread has only added fuel to the fire. 

- The endorsement of OnlyOffice as the de-facto, official online office suite integration with NextCloud over other alternatives such as Collabora Office, while not transparently disclosing the 20 connection limitation in the app description.
- The disappearance of Creative Commons content in the NextCloud docs (contributed by the community) in favor of hiding information such as deployment recommendations behind the Customer Portal, which requires a subscription from NextCloud GmbH to access.

Please read our response to @jospoortvliet's remarks at this link.
https://autoize.com/independent-open-source-consulting-vs-enterprise-subscriptions/

**Comment by karlitschek** [comment] 2020-02-04 18:02
Hi everyone, I would suggest to calm down and discuss the point one by one. Because several things are mixed together here.
First of all. I'm 100% sure that no one here wanted to offend anyone. So I suggest that we stay professional and not accuse each other.
It's true that some enterprise documentation is only available for customers. This is unfortunately a common practice in open source companies. We try to make sure that this only affect documentation for very very big installations that should not be relevant to normal users.
You can be sure that Nextcloud will never become open core. This is one of our fundamental principles. 
The problem with ONLYOFFICE is that this is not our software. It's provided by a different company which has decided that they want to go with the open core model. This is unfortunately outside our influence. We decided to take the community edition from them and make them easily available as a standard Nextcloud app. So everyone can benefit from a free office which is a huge step forward in my opinion. Unfortunately this comes with some consequences. The first is that the way we implemented it via PHP and binaries shipped as AppImage and called via the CLI during runtime comes with some performance issues. This is what Jos mentioned. We can't fix this at the moment without falling back to the old Docker installation which is more complex. The second issue is that their community edition has a build in limit of 20 connections. This is something we had to promise to respect. Please understand that this is not our idea but the result of the ONLYOFFICE open core business model.
If you think that ONLYOFFICE should get rid of the enterprise edition and and connection limits then you have to talk with them unfortunately. This is out of our influence. There is still the way to use the Collabora Docker container with Nextcloud which is also fully supported. Unfortunately the Collabora docker also comes with a compiled in 20 user restriction.
You really should complain to the other companies here and not to Nextcloud.
I hope this explains the situation better.

**Comment by hifihedgehog** [comment] 2020-02-05 19:38
> The second issue is that their community edition has a build in limit of 20 connections. This is something we had to promise to respect. Please understand that this is not our idea but the result of the ONLYOFFICE open core business model.
> 
> There is still the way to use the Collabora Docker container with Nextcloud which is also fully supported. Unfortunately the Collabora docker also comes with a compiled in 20 user restriction.
> You really should complain to the other companies here and not to Nextcloud.
> I hope this explains the situation better.

Respectfully, no, it doesn't. In the first place, as a silent lurker, I am piping up to let you know that I and others don't appreciate you inexplicably telling participants in this conversation to "calm down" when their conversation here thus far has been wholly detail-oriented in an effort to seek to understand, not shut them down, which is what your opening statement effectively accomplishes. Secondly, the statement from you above is a classic example of deny, differ and delay. What other companies do is their modus operandi and theirs alone and it is not an open invitation to follow their lead or pawn off their choices as an excuse for your own poor behavior that comes of your own accord. Collabora isn't ONLYOFFICE, and Nextcloud isn't ONLYOFFICE. Companies who decide to open themselves to the wild open west of open source need to realize that just because it fulfills a bullet point on their marketing to-do list, it absolutely does not exempt them of all the pros and cons that they will inevitably face of opening their codebase to the world at large. As such, users of an open source project can freely and openly (hence the definition) discuss all methods and procedures to modify the open source code base to suit their requirements and preferences without the least bit of concern of legal ramifications or social harassment in response to the pursuit of those actions. So yes, I understand ONLYOFFICE and Nextcloud are doing their best to diplomatically feed two beasts at the same time (paying commercial clientele and open source free users) without alienating either group... _but_ users here will continue to discuss and dissect ONLYOFFICE's code until this user limit workaround is found. It is only a matter of time and it **_will_** happen.

**Comment by kesselb** [comment] 2020-02-05 20:47
> users here will continue to discuss and dissect ONLYOFFICE's code until this user limit workaround is found. It is only a matter of time and it will happen... which it has.

A small detail: The article by autoize you posted is something different. Of course you can use that as backend for OnlyOffice too but this issue is (or was) about making the limitation of https://github.com/nextcloud/documentserver_community (also a backend for OnlyOffice but written in PHP) configurable. It's possible to remove the limitation without rebuilding anything: https://help.nextcloud.com/t/onlyoffice-community-edition-without-20-connections-limitation/59269/47

**Comment by SimonMGS** [comment] 2020-02-05 21:16
@jospoortvliet

Well, that seems to amount to essentially a rationalisation and defence of the open-core model in the name of pragmatism. I don’t want to get too drawn into that, as I think it’s a distraction from the point.  I can tell you that the [distinction between open-core and genuine open-source](https://www.redhat.com/en/blog/open-source-or-open-core-why-should-you-care) projects is of great significance to folks in the sectors that I deal with. Your PR position on this might play to a certain audience, but the things you’ve said in this thread will be quite alarming to some of those I consult with who have adopted Nextcloud (or were considering it).

With everything that Frank has said publicly before, and the rejection of open-core as part of the Nextcloud Values Statement, I think many people reasonably took it to mean that Nextcloud had taken clear position against open-core. That, as far as Nextcloud was concerned, the debate was settled.

From your commentary, I think we now need to consider those previous claims with a degree of skepticism. Spinning it as “not helping business users get things for free”, together with your attitude towards Autoize, I think is quite illuminating.


> But please don't take our promises out of context. We have committed to not doing an open core business model. Not to not work with anyone who does - the libraries Nextcloud builds on have all kinds of business models, too. We just look for license compatibility, the protection of our users is in the AGPL. We promised to not write proprietary code - but partners do, like our Outlook add-in partner, and even our official iOS client was fully proprietary for the first year or so, until we convinced our partner to open source it.
> So if you feel this is a slipperly slope, well, we were already far further down that slope on the day we launched our company than that we are with ONLYOFFICE.

It’s not simply a slippery slope argument. There is a distinction between third-parties who produce extensions beyond your control, and the software you choose to integrate as part of the default Nextcloud stack, and your relationship with them. What I’m suggesting, is that by integrating clearly open-core software as part of Nextcloud Hub’s default functionality, and applying the same restrictions to the Nextcloud fork of that software, that is blurring the line to such an extent that Nextcloud’s rejection open-core becomes meaningless. 

A skeptical person might look at this, and see that it’s quite a good way to get around the commitment against open-core: leave the core of Nextcloud truly free, then start adding restricted key functionality by integrating open-core third-party software, and doing a deal on the backend. And, as in the case of  Nextcloud Talk, having deeper ties to the “third party”. In that case, both Spreed and Nextcloud are related through Struktur AG, and Nextcloud Talk restricts functionality to the proprietary offering of Spreed.  With more Nextcloud functionality going the same way, one can see how this game might be played, and I think it raises some red flags for those who took Nextcloud seriously as a true open-source project.

**Comment by RamSamV** [comment] 2020-02-06 12:52
> Let me add: we always say we have the Red Hat business model, but actually we don't. We make our enterprise product freely available to everyone, unlike Red Hat where you'll have to either use Fedora or CentOS which might or might not be quite a bit behind. You can't get Red Hat Linux without paying at all. And perhaps we could make much more money if we followed that model, and we would be able to make Nextcloud much better much faster than we do today. Should we do that?

I've been following this discussion with interest, but here you are simply spreading FUD about Redhat and the community distributions. 

Fedora and CentOS are not "quite a bit behind". Fedora and CentOS Stream are in fact ahead of Redhat Enterprise, which conservatively adopts their code once they are satisfied that it is stable enough for enterprise use. Then there is CentOS itself, which is FOSS but similarly conservative in adopting stable code.

Both Fedora and CentOS have independent governing bodies, comprised of both Redhat and community representatives. This is an area where Nextcloud could improve by copying the model more closely, and I recall that Nextcloud did state that it would do so, some years ago.

**Comment by jospoortvliet** [comment] 2020-02-08 08:07
> Fedora and CentOS are not "quite a bit behind". Fedora and CentOS Stream are in fact ahead of Redhat Enterprise, which conservatively adopts their code once they are satisfied that it is stable enough for enterprise use. Then there is CentOS itself, which is FOSS but similarly conservative in adopting stable code.

Sorry, you're right, Fedora is obviously not behind - but usually ahead. I meant that to reflect CentOS, which is usually a bit behind on updates if I'm not mistaken, wasn't there a long delay getting the latest version out? I'm more of a openSUSE guy so I don't follow it closely, Mea Culpa if I was wrong about that.

I personally like the model of Red Hat, but I think my argument (that you get less 'for free' with that model) stands - we act like Canonical, giving everything away - what that means can be debated, fact is that Canonical's model is financially far less successful than that of SUSE with SLE vs openSUSE and Red Hat with RHEL vs Fedora. So maybe a Nextcloud Enterprise Collaboration or something, that only customers can get, like with RHEL, is something we should do.

**Comment by RamSamV** [comment] 2020-02-08 10:17
As far as I’m concerned you are free to choose any model you like.  Am I wrong in thinking that you already doing this, with an enterprise build only available to customers?

> What is Nextcloud Enterprise?
> 
> To better deliver on the needs of our customers, they have access to a special Nextcloud Enterprise build pre-configured, optimized and hardened for the special needs of large scale, production-critical enterprise deployments. Nextcloud Enterprise provides the following key benefits:
> 
>    * Improved reliability. Nextcloud Enterprise receives additional quality assurance to provide the highest degree of reliability and offers a longer life cycle. 
>    * Improved scalability. Nextcloud Enterprise is pre-configured and optimized for the needs of large scale production at enterprises, rather than home users. 
>    * Improved security. Nextcloud Enterprise customers get priority access to security and stability fixes to guarantee smooth operation out of the box. 
>    * Certified integrity. Nextcloud Enterprise is a guaranteed proven, certified code base for legal compliance like GDPR and HIPAA. 

Redhat do something similar though they don’t withhold access to security and stability fixes. But remember that they share the RHEL codebase and sponsor the independent governing bodies of Fedora and CentOS, with a balance of representatives from the company and the community. The Fedora community focuses on the cutting edge, and CentOS on stability. They can differ from the RHEL build but only as far as the communities decide to adopt things differently. There is no attempt to restrict  anything or limit the number of users which would obviously undermine the entire co-operative concept. RHEL is distinguished mainly by being the professionally supported version, and large enterprises need the security of purchasing professional support and the extra level of QA, which seems to be what you are also doing already.

Am I correct that Nextcloud originally said there would be an independent foundation set up to govern development in partnership with the community?

**Comment by fkohrt** [comment] 2020-02-10 12:32
@karlitschek 

> Unfortunately the Collabora docker also comes with a compiled in 20 user restriction.

I believe there's no hard limit, at least not for Collabora CODE. One is presented with the following warning:

![Collabora_CODE_Warning](https://user-images.githubusercontent.com/12914806/74149653-8d29d600-4c08-11ea-97e5-4b8db17bd386.png)

But it can be dismissed and it's still possible to open more than 10 documents or 20 connections:

![Collabora_Code_Admin_Console](https://user-images.githubusercontent.com/12914806/74150005-5dc79900-4c09-11ea-99ce-67f7cf050b78.png)

This is also what TDF suggest:

> TDF is keen to avoid situations where an unsuitable version is deployed at scale, so when used in what would be likely to imply an enterprise situation - more than 10 concurrent documents and/or more than 20 connections - LibreOffice Online will display a prominent "not supported" warning and a link to this page, while continuing to function.

see [www.libreoffice.org/download/libreoffice-online/](https://www.libreoffice.org/download/libreoffice-online/)

**Comment by SimonMGS** [comment] 2020-02-10 20:52
That's a somewhat better way of doing it, but TBH I'd take that with a pinch of salt, too. I wouldn't be surprised if it's virtually the same code, as with OnlyOffice Community.

With regard to Redhat, I think the important thing is that the bid for enterprise customers is all carrot and no stick - there's nothing restricted (which would never fly with the community), and major enterprise customers are naturally going to want the reassurance of a relationship and support from an established corporation, with its own reputation and business on the line.

**Comment by PackElend** [comment] 2020-02-11 08:54
> A skeptical person might look at this, and see that it’s quite a good way to get around the commitment against open-core: leave the core of Nextcloud truly free, then start adding restricted key functionality by integrating open-core third-party software, and doing a deal on the backend. And, as in the case of Nextcloud Talk, having deeper ties to the “third party”. In that case, both Spreed and Nextcloud are related through Struktur AG, and Nextcloud Talk restricts functionality to the proprietary offering of Spreed. With more Nextcloud functionality going the same way, one can see how this game might be played, and I think it raises some red flags for those who took Nextcloud seriously as a true open-source project.

I would say that is all in a nutshell. 

In regard to Talk. Where a door closes another is open. Rocket.Chat GSoC 2019 work ended in deeper integration without limitation, may they going to be a serious competitor for Talk.

**Comment by sean-sullivan1** [comment] 2020-02-14 13:05
Just in case someone comes here looking for how to change / remove the 20 user restriction, I'm going to quote Cloudy1 here. Note... this is specifically for the Community Edition app not for docker image or manually compiling from source.

> I changed the following in nextcloud/apps/documentserver_community/:
> 
> lib/Controller/StaticController.php (line 92):
> } else if ($this->sessionManager->getSessionCount() >= 20) {
> 
> lib/XHRCommand/AuthCommand.php (line 37):
> const MAX_CONNECTIONS = 20
> 
> If you also want to change the message:
> js/sessionlimit.js:
> OC.Notification.show(t("documentserver", "The community document server only supports up to 20 concurrent sessions"), {
> 
> Increasing the limits in these lines works for me. I’m not sure for what each of the occurences is exactly, but I just set both to the same high number.

**Comment by jospoortvliet** [comment] 2020-02-20 13:39
> Redhat do something similar though they don’t withhold access to security and stability fixes. But remember that they share the RHEL codebase and sponsor the independent governing bodies of Fedora and CentOS, with a balance of representatives from the company and the community. The Fedora community focuses on the cutting edge, and CentOS on stability. They can differ from the RHEL build but only as far as the communities decide to adopt things differently. There is no attempt to restrict anything or limit the number of users which would obviously undermine the entire co-operative concept.

That's nice in theory, but of course in reality RH steers Fedora and it is mostly a test bed for RHEL and its engineers. I know plenty of RH people and people (formerly) active in the Fedora community to have no illusions about this... And I think it is fine, Fedora is great for private users. CentOS used to not get any RH support until some years ago - it's what RH uses to undercut Canonical and keep them from challenging them, I suppose.

> RHEL is distinguished mainly by being the professionally supported version, and large enterprises need the security of purchasing professional support and the extra level of QA, which seems to be what you are also doing already.

Yeah, to a degree - but the difference between RHEL and Fedora is far, far larger than between the Nextcloud enterprise build and the normal build - that difference is minimal. And we'd like to be able to keep that minimal and keep doing everything in the open and for free, even though that means less developers working on Nextcloud.

> Am I correct that Nextcloud originally said there would be an independent foundation set up to govern development in partnership with the community?

Kind of, it would just hold the trademark. When we're a billion dollar company we can probably also afford doing the things RH does, but for now we're not.

From another commenter:
> A skeptical person might look at this, and see that it’s quite a good way to get around the commitment against open-core: leave the core of Nextcloud truly free, then start adding restricted key functionality by integrating open-core third-party software, and doing a deal on the backend. 

Your 'skepticism' seems to completely miss what open source is about. You can contribute to Nextcloud and do with it what you want. THAT is what makes us an true Open Source project. What **you** can do with it. Not what **we do for you.** That we don't work for you (or others) for free doesn't make Nextcloud any less of an open source project. At least, last time I checked, the OSI or FSF didn't include that in their definitions.

> And, as in the case of Nextcloud Talk, having deeper ties to the “third party”. In that case, both Spreed and Nextcloud are related through Struktur AG, and Nextcloud Talk restricts functionality to the proprietary offering of Spreed. With more Nextcloud functionality going the same way, one can see how this game might be played, and I think it raises some red flags for those who took Nextcloud seriously as a true open-source project.

Talk has no 'restrictions' added to it. The technology it builds on has restrictions, but those only come in to play at a certain scale. And at that point, yes, there are other products out there that can fix that.

We have a million useful things we could do, and the lowest on that list is rewriting a product from another company so potential customers don't have to pay money for using Nextcloud at scale. We build great user interfaces, not back-ends (that's why we also don't build a office document server or a mail server). 

We're not opposed to somebody else doing it - if you wish to write an alternative back-end, go ahead, have fun, we're happy to support it in Talk, too. Very open source, that is. But I really can't feel bad that we are not spending 5 or 10 FTE years for... what exactly do we get out of that, can you explain that to me? Going out of our way to work for free for large companies is suddenly mandatory if you want to be a True Open Source project these days? Sorry, but all these crocodile tears make no sense to me.

I'll close this now, it has served its purpose and then some.

**Closed by jospoortvliet** 2020-02-20 13:39 UTC
