### ISSUE TITLE
It doesn't even download / Install

### ISSUE THREAD

**Issue by macalde** [nextcloud/documentserver_community#169] opened 2020-09-06 04:51 UTC
Keep getting the below error. Haven't been able to install for months now!

cURL error 28: Operation timed out after 120154 milliseconds with 306248916 out of 314306683 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by SchokoShampoo** [comment] 2020-09-17 15:32
Try to install via the commandline
The app is a little bit to big to download via the webinterface. It takes too long and so the server decides to cancel the process.
https://nextcloud.com/blog/how-to-install-onlyoffice-in-nextcloud-hub-and-new-integration-feature/
There you can find the needed commands for the installation

**Comment by icewind1991** [comment] 2020-10-06 13:04
Closing as duplicate of #26

**Closed** 2020-10-06 13:04 UTC
