### ISSUE TITLE
Will updates to newer versions of OnlyOffice occur for documentserver_community?

### ISSUE THREAD

**Issue by greavette** [nextcloud/documentserver_community#134] opened 2020-05-14 15:29 UTC
Hello Team,

Thank you for providing documentserver_community app as an easy way to install OnlyOffice on Nextcloud. I've had OnlyOffice installed on a separate server but using this App is much easier!  

I've noticed that documentserver_community is behind the latest release of OnlyOffice.  Will documentserver_community be a living project and keep up to date with OnlyOffice releases? 

Also I really miss not having a spell check on OnlyOffice. I see others have mentioned this fact in documentserver_community incidents but I've not seen an official reply on what the direction is for documentserver_community to add in spellcheck.  This seems like a critical function when editing documents.  

Thank you in advance for any information you can provide me.

**Comment by kesselb** [comment] 2020-05-20 17:44
Looks like a duplicate of https://github.com/nextcloud/documentserver_community/issues/104 to me.

**Comment by icewind1991** [comment] 2020-10-06 13:15
Yes, the version of the bundled onlyoffice bits will be updated "every now and then".

Spellcheck is likely to remain unsupported for the foreseeable future.

**Closed by icewind1991** 2020-10-06 13:15 UTC
Labels: help wanted
