### ISSUE TITLE
Spell check, no function in word documents

### ISSUE THREAD

**Issue by horstvogel** [nextcloud/documentserver_community#38] opened 2020-01-24 17:58 UTC
Spell check, no function in word documents, 
With an external document server, this works fine

Nextcloud 18, Ngnix, PHP 7.3, Ubuntu 18.04, Documents Server 0.1.3

**Comment by icewind1991** [comment] 2020-01-28 13:14
Duplicate of https://github.com/nextcloud/documentserver_community/issues/14

**Closed by icewind1991** 2020-01-28 13:14 UTC
