### ISSUE TITLE
cannot update to 0.1.7 from nextcloud apps

### ISSUE THREAD

**Issue by brdobrdo** [nextcloud/documentserver_community#158] opened 2020-07-01 07:05 UTC
When I click on the community server update button in Nextcloud apps the small wheel turns for a while then stops. Nothing happens at the end.

Nextcloud 18.0.4.
Failed update: Community server 0.1.7

**Comment by Dugaa** [comment] 2020-07-05 16:11
I have the same Problem

**Comment by InsaneJ** [comment] 2020-07-07 13:56
Same problem here. You click the "Update to 0.1.7" button, wait for a while and then there's a small pop-up at the right-top corner stating: "An error occured during the request. Unable to proceed.".

**Comment by brdobrdo** [comment] 2020-07-07 16:39
I solved it by a workaround.

1. Downloaded this file (0.1.7 for NC 18.0.0 in my case) https://github.com/nextcloud/documentserver_community/releases/download/v0.1.7/documentserver_community.tar.gz
2. Upload to nextcloud apps folder where your current community server folder is and extract (In my case NC is installed on shared hosting and I am doing all of this using cpanel and file manager)
3. Go to your nextcloud ip ... when it opens it says that it needs to do an update (or upgrade) .... OK and the process finishes with an updated community server

It was done this way, It works, but I don't know if this does some damage...

During the failed try when I clicked on update button I monitored the upload through cpanel in .cagefs folder . It downloads fine, but then the file disappears and nothing happens. 

I had to install document server this way too. It was something to do with document server being a big file...

**Comment by melgit** [comment] 2020-08-14 20:48
Same problem here after updating from 18 to 19.01. Is this workaround future proof ?

**Comment by brdobrdo** [comment] 2020-08-15 06:13
The app and everything else still work, if that is what you meant.

**Comment by icewind1991** [comment] 2020-10-06 13:05
Closing as duplicate of #26

**Closed by icewind1991** 2020-10-06 13:05 UTC
