### ISSUE TITLE
Document server fails with "./x2t: not found"

### ISSUE THREAD

**Issue by fthl** [nextcloud/documentserver_community#18] opened 2020-01-19 13:11 UTC
Unfortunately even with 0.1.2 I still get the "Community document server is not supported for this instance, please setup and configure an external document server" error.

This is the log entry in nc-log:

`OCA\DocumentServer\Document\DocumentConversionException: sh: ./x2t: not found

    /web/nextcloud/apps/documentserver_community/lib/Document/ConverterBinary.php - line 64:

    OCA\DocumentServer\Document\ConverterBinary->run("")

    /web/nextcloud/apps/documentserver_community/lib/Controller/StaticController.php - line 90:

    OCA\DocumentServer\Document\ConverterBinary->test()

    /web/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 170:

    OCA\DocumentServer\Controller\StaticController->webApps("apps/api/documents/api.js")

    /web/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Document ... {}, "webApps")

    /web/nextcloud/lib/private/AppFramework/App.php - line 125:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Document ... {}, "webApps")

    /web/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OCA\\Docume ... r", "webApps", OC\AppFramew ... {}, { path: "app ... "})

    <<closure>>

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ path: "app ... "})

    /web/nextcloud/lib/private/Route/Router.php - line 299:

    call_user_func(OC\AppFramew ... {}, { path: "app ... "})

    /web/nextcloud/lib/base.php - line 1008:

    OC\Route\Router->match("/apps/docum ... s")

    /web/nextcloud/index.php - line 38:

    OC::handleRequest()`

Any help is appreciated!

**Comment by Xeyk** [comment] 2020-01-19 13:33
Same issue here. I tried completely removing OnlyOffice and the DocumentServer, confirmed that both directories were removed from the apps folder, and reinstalled them.

This time around, though, it's not showing anything in the logs. No failure message or anything of the sort.

**Comment by krm87** [comment] 2020-01-20 13:27
Encountered the same issue.
After messing around with the path in php scripts I decided to see if I could execute the file in the docker container. I couldn't.

I'm using linuxserver.io docker build of nextcloud and its alpine/musl based, that seems to be the problem.
Not 100% sure but no time now to investigate further.

**Comment by Xeyk** [comment] 2020-01-20 17:54
@krm87 did you just set up the plugin in a separate container, or did you do a full onlyoffice install in a new container?

**Comment by krm87** [comment] 2020-01-20 18:26
> @krm87 did you just set up the plugin in a separate container, or did you do a full onlyoffice install in a new container?

I kept onlyoffice in nextcloud and setup a new docker container with onlyoffice document server. Created a network for the nextcloud and onlyoffice documentserver containers and configured onlyoffice in nextcloud server settings accordingly.
I also had to disable ssl verification in documentserver.

**Comment by jdsmall25** [comment] 2020-01-21 20:38
I also have this issue.
Nextcloud fpm-alpine docker image behind a docker nginx reverse proxy on a separate host. I currently run Collabora in a separate docker container which has been running well and wanted to checkout OnlyOffice as part of the v18 release. No joy.

**Comment by skjnldsv** [comment] 2020-01-22 07:35
duplicate of https://github.com/nextcloud/documentserver_community/issues/10

**Closed by skjnldsv** 2020-01-22 07:35 UTC
