### ISSUE TITLE
Community Document Server - cURL error 28: Operation timed out after 120000 millisecond

### ISSUE THREAD

**Issue by NukeManDan** [nextcloud/documentserver_community#133] opened 2020-05-13 08:50 UTC
https://help.nextcloud.com/t/community-document-server-curl-error-28-operation-timed-out-after-120000-millisecond/80589

I also get this (see thread in link ^^) on trying to install the app from the webui : <MY_CLOUD_URL>/settings/apps/app-bundles/documentserver_community

I am able to get somewhere between 1/2 and 3/4 of the data

![image](https://user-images.githubusercontent.com/35669742/81791860-82f7cc00-94c4-11ea-9326-d6421b225204.png)

**Comment by yorichyrich** [comment] 2020-06-08 02:35
I am in the same boat here, my NextCloud instance was installed via Snap on Ubuntu and I can't edit the Client.php file in htaccess file.  The timeout needs to be set longer, please!

Thanks!!

**Comment by nicolas-tourrette** [comment] 2020-06-23 18:45
Found on https://help.nextcloud.com/t/curl-error-28-operation-timed-out-after-xxxxxx-milliseconds-with-xxxxxx-out-of-xxxxxx-bytes-received-see-http-curl-haxx-se-libcurl-c-libcurl-errors-html/67621/4 :

A change in the /lib/private/Installer.php file may help
$ timeout = $ this-> isCLI? 0: 120; for example: 300

I can only change in this file helped 😃 

And it helps me to solve the problem. My value is 1200.

**Comment by Stratus3D** [comment] 2020-07-15 01:40
I am experiencing the same issue. I changed that timeout value in `/lib/private/Installer.php` to 1200 and it still fails for me.

**Comment by nicolas-tourrette** [comment] 2020-07-16 12:01
Perhaps you should increase again the value, depends on your server Internet connection. The worse it is, heighest athe value has to be...

**Comment by icewind1991** [comment] 2020-10-06 13:06
Closing as duplicate of #26

**Closed by icewind1991** 2020-10-06 13:06 UTC

**Comment by Naaktgeboren** [comment] 2022-04-17 04:56
> I am experiencing the same issue. I changed that timeout value in `/lib/private/Installer.php` to 1200 and it still fails for me.

In case you are also wondering where the above mentioned file is exactly, it is in the 'nextcloud' folder in the web service space on your hosting machine.

In my Ubuntu+Apache2 case, the full address is: /var/www/nextcloud/lib/private/Installer.php

**Comment by saurabii** [comment] 2023-02-03 12:22
This Works for ME.
In my Ubuntu+Apache2 case, the full address is: /var/www/nextcloud/lib/private/Installer.php
change Time out value: 120 to 1200.. and it's worked.

**Comment by thomasbonsirven** [comment] 2023-04-09 05:53
Hello,

Juste for informations : 

If you are edit the timeout un Installer.php, ans it's not work, maybe beacause need other dependance.

Try to install make, curl, rpm2cpio, and cpio, is required.
Command for debian, unbuntu and more : 

`sudo apt install make curl rpm2cpio cpio`

Its work for me.
