### ISSUE TITLE
Does not save changes to documents

### ISSUE THREAD

**Issue by lagethomas** [nextcloud/documentserver_community#120] opened 2020-04-22 15:33 UTC
When creating files or the system does not save any changes made. When you open a web interface, the data is there, but when you access the document locally (Office for example), the document is blank.
It is not possible to create a document as you can create a web interface, edit, the data is there, but accessing locally there is only one empty file. For now, you'll use the dedicated Document Server that works today.

**Comment by kesselb** [comment] 2020-04-28 08:43
Closing as duplicate of #12

**Closed by kesselb** 2020-04-28 08:43 UTC
