### ISSUE TITLE
PHP error while adding fonts

### ISSUE THREAD

**Issue by th3noname** [nextcloud/documentserver_community#40] opened 2020-01-25 10:18 UTC
I tried to add fonts to the document server, but I only get the following error:

```
stream_get_contents():  supplied resource is not a valid stream resource at  /var/www/nextcloud/nextcloud/apps/documentserver_community/lib/Document/FontManager.php#63
fclose(): supplied resource is not a valid stream resource at /var/www/nextcloud/nextcloud/apps/documentserver_community/lib/Document/FontManager.php#62
```

Using the follwoing command:

```sudo -u www-data php occ documentserver:fonts --add /path/to/Fonts/Crimson_Text/CrimsonText-SemiBold.ttf```

**Comment by th3raid0r** [comment] 2020-01-26 04:43
I am also getting this. Perhaps related to https://github.com/nextcloud/documentserver_community/issues/36 ?

**Comment by th3raid0r** [comment] 2020-01-26 05:23
I have a theory that moving down to the simpler popen() function may mitigate this, but depending on the roadmap - that might not be desired. I'll test it and report back.

**Comment by th3raid0r** [comment] 2020-01-26 07:12
This error is being caused by incorrect permission on the `./tools/allfontsgen` - it lacks the execution bit necessary to run the program.

Simply run this:

`sudo chmod -x $NEXTCLOUD_DIR/apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin/allfontsgen`

After that the OCC command runs correctly. 

**However** - don't attempt to use `find` and `xarg` to load in a folder full of fonts like I did. The application currently re-generates ALL fonts for each now font you load in - the operation is VERY memory intensive and crashed my PC.

For bulk upload - copy a folder of all your favorite fonts into:
`nextcloud/apps/documentserver_community/3rdparty/onlyoffice/documentserver/core-fonts/` and then load in a single font with the OCC command to run `allfontsgen`.

**Comment by icewind1991** [comment] 2020-01-27 12:52
Should be fixed with 740bd62a2500dda1a69a849532025607ef8dbf2e

> However - don't attempt to use find and xarg to load in a folder full of fonts like I did. The application currently re-generates ALL fonts for each now font you load in - the operation is VERY memory intensive and crashed my PC.

in 0.1.4 the command will allow adding multiple fonts in one go (f1b67fe)

**Closed by icewind1991** 2020-01-27 12:52 UTC

**Comment by sankayop** [comment] 2020-04-05 12:00
> This error is being caused by incorrect permission on the `./tools/allfontsgen` - it lacks the execution bit necessary to run the program.
> 
> Simply run this:
> 
> `sudo chmod -x $NEXTCLOUD_DIR/apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin/allfontsgen`
> 
> After that the OCC command runs correctly.
> 
> **However** - don't attempt to use `find` and `xarg` to load in a folder full of fonts like I did. The application currently re-generates ALL fonts for each now font you load in - the operation is VERY memory intensive and crashed my PC.
> 
> For bulk upload - copy a folder of all your favorite fonts into:
> `nextcloud/apps/documentserver_community/3rdparty/onlyoffice/documentserver/core-fonts/` and then load in a single font with the OCC command to run `allfontsgen`.

Hi all,
referring to the solution above, I can't find the allfontsgen file?!
`
[sankayop@cloud /var/www/nextcloud]$ sudo chmod -x apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin/           
AllFonts.js             font_selection.bin      libPdfReader.so         libgraphics.so
DoctRenderer.config     icudtl.dat              libPdfWriter.so         libicudata.so.58
HtmlFileInternal/       libDjVuFile.so          libUnicodeConverter.so  libicuuc.so.58
docbuilder              libHtmlFile.so          libXpsFile.so           libkernel.so
`
I have NC 18.0.3 installed on Freebsd12.1 amd64 but it does not make any difference since the file is part of the downloaded package, right?

Other information, I always need to download 3 times Document Community Server to be able to enable it.
Although, there are always a bunch of error (cf. https://github.com/nextcloud/documentserver_community/issues/54 and https://github.com/nextcloud/documentserver_community/issues/40)

My main objective is to get OnlyOffice to work inside NC and until now, no sign of it.

Thanks for your help if you have any idea...
Yop

**Comment by samtuke** [comment] 2020-05-13 17:36
This was also unclear to me
