### ISSUE TITLE
Nextcloud 18 OnlyOffice is loading forever

### ISSUE THREAD

**Issue by gcommit** [nextcloud/documentserver_community#29] opened 2020-01-22 14:15 UTC
Hi,

i am running a Nextcloud 18 (upgraded from 17.0.0 to 18.0.0) and tried to install "onlyoffice" and "community document server" to work with it. The installation just went fine and the serviceadress is filled in automatically, which is nice. But when i want to open a file it's loading into "onlyoffice" but is showing the loading screen forever. 

I had a look at the network interface in my browser and saw this:

`POST https://MY-URL-DE/index.php/apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/2281804892/c/670/ws2b4xun/xhr_send?t=1579701898108 500 (Internal Server Error)
`
### Steps to reproduce
1. Start Nextcloud 17.0.0 with S3 as primary storage
2. Upgrade to 18.0.0
3. Try to install and use Onlyoffice

Is there something i am missing or is this a real bug?

**Comment by icewind1991** [comment] 2020-01-24 14:55
Can you try again with 0.1.3

**Comment by gcommit** [comment] 2020-01-25 16:43
I will. I‘ll let you know when i have tested it.

**Comment by KoljaL** [comment] 2020-01-27 10:08
Running new installed NC18 and get this after click on install: Es ist ein Fehler bei der Anfrage aufgetreten. Es kann nicht fortgefahren werden.

**Comment by mikshepard** [comment] 2020-01-29 16:19
Same issue, here is what I found in the logs:

> {"reqId":"dNVX7fYjQ5DsDgcFlzlR","level":1,"time":"2020-01-29T09:54:43-06:00","remoteAddr":"X.X.X.X","user":"admin","app":"no app in context","method":"POST","url":"/apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/2216742121/c/932/2oflraqh/xhr_send?t=1580313284166","message":"Deprecated event type for \\OCP\\Files::postWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}

> {"reqId":"dNVX7fYjQ5DsDgcFlzlR","level":3,"time":"2020-01-29T09:54:43-06:00","remoteAddr":"X.X.X.X","user":"admin","app":"index","method":"POST","url":"/apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/2216742121/c/932/2oflraqh/xhr_send?t=1580313284166","message":{"Exception":"OCP\\Files\\NotFoundException","Message":"/appdata_ocul0lyxt4n4/documentserver_community/doc_2216742121/Editor.bin","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Files/Node/Folder.php","line":137,"function":"get","class":"OC\\Files\\Node\\Root","type":"->","args":["/appdata_ocul0lyxt4n4/documentserver_community/doc_2216742121/Editor.bin"]},{"file":"/var/www/nextcloud/lib/private/Files/SimpleFS/SimpleFolder.php","line":74,"function":"get","class":"OC\\Files\\Node\\Folder","type":"->","args":["Editor.bin"]},{"file":"/var/www/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php","line":99,"function":"getFile","class":"OC\\Files\\SimpleFS\\SimpleFolder","type":"->","args":["Editor.bin"]},{"file":"/var/www/nextcloud/apps/documentserver_community/lib/XHRCommand/AuthCommand.php","line":141,"function":"getDocumentForEditor","class":"OCA\\DocumentServer\\Document\\DocumentStore","type":"->","args":[2216742121,{"__class__":"OC\\Files\\Node\\File"},"docx"]},{"file":"/var/www/nextcloud/apps/documentserver_community/lib/XHRCommand/CommandDispatcher.php","line":45,"function":"handle","class":"OCA\\DocumentServer\\XHRCommand\\AuthCommand","type":"->","args":[{"type":"auth","docid":"2216742121","documentCallbackUrl":"https://myserver.mydomain.com/apps/onlyoffice/track?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJhZG1pbiIsImZpbGVJZCI6MTY4ODE3OSwiZmlsZVBhdGgiOiJcL0RvY3VtZW50c1wvVGVzdC5kb2N4Iiwic2hhcmVUb2tlbiI6bnVsbCwiYWN0aW9uIjoidHJhY2sifQ.wQkT9s95FVUur3NvbzvbRh3C8oPHlWyHtfAyVfOKnlE","token":"fghhfgsjdgfjs","user":{"id":"ocul0lyxt4n4_admin","username":"admin","firstname":null,"lastname":null,"indexUser":-1},"editorType":0,"lastOtherSaveTime":-1,"block":[],"sessionId":null,"sessionTimeConnect":null,"sessionTimeIdle":0,"documentFormatSave":65,"view":false,"isCloseCoAuthoring":false,"openCmd":{"c":"open","id":"2216742121","userid":"ocul0lyxt4n4_admin","format":"docx","url":"https://myserver.mydomain.com/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlSWQiOjE2ODgxNzksInVzZXJJZCI6ImFkbWluIiwic2hhcmVUb2tlbiI6bnVsbCwiYWN0aW9uIjoiZG93bmxvYWQifQ.sthWEFefXLbsrnohNUtQ0F878kmKer9G4Gm_OeK7z6s","title":"Test.docx","nobase64":true},"lang":null,"mode":null,"permissions":{"edit":true}},{"__class__":"OCA\\DocumentServer\\Channel\\Session"},{"__class__":"OCA\\DocumentServer\\IPC\\IPCChannel"},{"__class__":"OCA\\DocumentServer\\Channel\\IPCMulticast"},{"__class__":"OCA\\DocumentServer\\XHRCommand\\CommandDispatcher"}]},{"file":"/var/www/nextcloud/apps/documentserver_community/lib/Channel/Channel.php","line":106,"function":"handle","class":"OCA\\DocumentServer\\XHRCommand\\CommandDispatcher","type":"->","args":[{"type":"auth","docid":"2216742121","documentCallbackUrl":"https://myserver.mydomain.com/apps/onlyoffice/track?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJhZG1pbiIsImZpbGVJZCI6MTY4ODE3OSwiZmlsZVBhdGgiOiJcL0RvY3VtZW50c1wvVGVzdC5kb2N4Iiwic2hhcmVUb2tlbiI6bnVsbCwiYWN0aW9uIjoidHJhY2sifQ.wQkT9s95FVUur3NvbzvbRh3C8oPHlWyHtfAyVfOKnlE","token":"fghhfgsjdgfjs","user":{"id":"ocul0lyxt4n4_admin","username":"admin","firstname":null,"lastname":null,"indexUser":-1},"editorType":0,"lastOtherSaveTime":-1,"block":[],"sessionId":null,"sessionTimeConnect":null,"sessionTimeIdle":0,"documentFormatSave":65,"view":false,"isCloseCoAuthoring":false,"openCmd":{"c":"open","id":"2216742121","userid":"ocul0lyxt4n4_admin","format":"docx","url":"https://myserver.mydomain.com/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlSWQiOjE2ODgxNzksInVzZXJJZCI6ImFkbWluIiwic2hhcmVUb2tlbiI6bnVsbCwiYWN0aW9uIjoiZG93bmxvYWQifQ.sthWEFefXLbsrnohNUtQ0F878kmKer9G4Gm_OeK7z6s","title":"Test.docx","nobase64":true},"lang":null,"mode":null,"permissions":{"edit":true}},{"__class__":"OCA\\DocumentServer\\Channel\\Session"},{"__class__":"OCA\\DocumentServer\\IPC\\IPCChannel"},{"__class__":"OCA\\DocumentServer\\Channel\\IPCMulticast"}]},{"file":"/var/www/nextcloud/apps/documentserver_community/lib/Controller/SessionController.php","line":114,"function":"handleCommand","class":"OCA\\DocumentServer\\Channel\\Channel","type":"->","args":[{"type":"auth","docid":"2216742121","documentCallbackUrl":"https://myserver.mydomain.com/apps/onlyoffice/track?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJhZG1pbiIsImZpbGVJZCI6MTY4ODE3OSwiZmlsZVBhdGgiOiJcL0RvY3VtZW50c1wvVGVzdC5kb2N4Iiwic2hhcmVUb2tlbiI6bnVsbCwiYWN0aW9uIjoidHJhY2sifQ.wQkT9s95FVUur3NvbzvbRh3C8oPHlWyHtfAyVfOKnlE","token":"fghhfgsjdgfjs","user":{"id":"ocul0lyxt4n4_admin","username":"admin","firstname":null,"lastname":null,"indexUser":-1},"editorType":0,"lastOtherSaveTime":-1,"block":[],"sessionId":null,"sessionTimeConnect":null,"sessionTimeIdle":0,"documentFormatSave":65,"view":false,"isCloseCoAuthoring":false,"openCmd":{"c":"open","id":"2216742121","userid":"ocul0lyxt4n4_admin","format":"docx","url":"https://myserver.mydomain.com/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlSWQiOjE2ODgxNzksInVzZXJJZCI6ImFkbWluIiwic2hhcmVUb2tlbiI6bnVsbCwiYWN0aW9uIjoiZG93bmxvYWQifQ.sthWEFefXLbsrnohNUtQ0F878kmKer9G4Gm_OeK7z6s","title":"Test.docx","nobase64":true},"lang":null,"mode":null,"permissions":{"edit":true}}]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"xhrSend","class":"OCA\\DocumentServer\\Controller\\SessionController","type":"->","args":[null,"2216742121","932","2oflraqh"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Controller\\DocumentController"},"xhrSend"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Controller\\DocumentController"},"xhrSend"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\DocumentServer\\Controller\\DocumentController","xhrSend",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"documentId":"2216742121","serverId":"932","sessionId":"2oflraqh","_route":"documentserver_community.Document.xhrSend"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"documentId":"2216742121","serverId":"932","sessionId":"2oflraqh","_route":"documentserver_community.Document.xhrSend"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"documentId":"2216742121","serverId":"932","sessionId":"2oflraqh","_route":"documentserver_community.Document.xhrSend"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/2216742121/c/932/2oflraqh/xhr_send"]},{"file":"/var/www/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/lib/private/Files/Node/Root.php","Line":203,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}

> {"reqId":"HKv6vy29RvjTRUJwYoCb","level":1,"time":"2020-01-29T09:54:43-06:00","remoteAddr":"X.X.X.X","user":"admin","app":"no app in context","method":"POST","url":"/apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/2216742121/c/932/2oflraqh/xhr?t=1580313284439","message":"Deprecated event type for OCA\\User_LDAP\\User\\User::postLDAPBackendAdded: null","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}

**Comment by pieter-groeneweg** [comment] 2020-01-30 10:10
What I get from clicking the document to open till I stop it manually by selecting something else in Nextcloud (in this, select the settings to see the logs..)

```
{"reqId":"qGSikmFOmXuiyZzOQmUi","level":0,"time":"2020-01-30T10:29:30+01:00","remoteAddr":"111.222.333.444","user":"######","app":"onlyoffice","method":"GET","url":"/index.php/apps/onlyoffice/ajax/config/6?filePath=%2FDocuments%2FAbout.odt&inframe=2","message":"Config is generated for: 6 with key 1922872674","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}
{"reqId":"zeHZfi9nNVOCGgbjdVqS","level":1,"time":"2020-01-30T10:29:32+01:00","remoteAddr":"111.222.333.444","user":"######","app":"no app in context","method":"POST","url":"/index.php/apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/1922872674/c/198/dq44hdvv/xhr_send?t=1580376572764","message":"Deprecated event type for \\OCP\\Files::preWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}
{"reqId":"zeHZfi9nNVOCGgbjdVqS","level":1,"time":"2020-01-30T10:29:32+01:00","remoteAddr":"111.222.333.444","user":"######","app":"no app in context","method":"POST","url":"/index.php/apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/1922872674/c/198/dq44hdvv/xhr_send?t=1580376572764","message":"Deprecated event type for \\OCP\\Files::preCreate: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}
{"reqId":"zeHZfi9nNVOCGgbjdVqS","level":1,"time":"2020-01-30T10:29:33+01:00","remoteAddr":"111.222.333.444","user":"######","app":"no app in context","method":"POST","url":"/index.php/apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/1922872674/c/198/dq44hdvv/xhr_send?t=1580376572764","message":"Deprecated event type for \\OCP\\Files::postWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}
{"reqId":"zeHZfi9nNVOCGgbjdVqS","level":1,"time":"2020-01-30T10:29:33+01:00","remoteAddr":"111.222.333.444","user":"######","app":"no app in context","method":"POST","url":"/index.php/apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/1922872674/c/198/dq44hdvv/xhr_send?t=1580376572764","message":"Deprecated event type for \\OCP\\Files::postCreate: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}
{"reqId":"zeHZfi9nNVOCGgbjdVqS","level":1,"time":"2020-01-30T10:29:33+01:00","remoteAddr":"111.222.333.444","user":"######","app":"no app in context","method":"POST","url":"/index.php/apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/1922872674/c/198/dq44hdvv/xhr_send?t=1580376572764","message":"Deprecated event type for \\OCP\\Files::preWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}
{"reqId":"zeHZfi9nNVOCGgbjdVqS","level":1,"time":"2020-01-30T10:29:33+01:00","remoteAddr":"111.222.333.444","user":"######","app":"no app in context","method":"POST","url":"/index.php/apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/1922872674/c/198/dq44hdvv/xhr_send?t=1580376572764","message":"Deprecated event type for \\OCP\\Files::preCreate: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}
{"reqId":"zeHZfi9nNVOCGgbjdVqS","level":1,"time":"2020-01-30T10:29:33+01:00","remoteAddr":"111.222.333.444","user":"######","app":"no app in context","method":"POST","url":"/index.php/apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/1922872674/c/198/dq44hdvv/xhr_send?t=1580376572764","message":"Deprecated event type for \\OCP\\Files::postWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}
{"reqId":"zeHZfi9nNVOCGgbjdVqS","level":1,"time":"2020-01-30T10:29:33+01:00","remoteAddr":"111.222.333.444","user":"######","app":"no app in context","method":"POST","url":"/index.php/apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/1922872674/c/198/dq44hdvv/xhr_send?t=1580376572764","message":"Deprecated event type for \\OCP\\Files::postCreate: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}
{"reqId":"zeHZfi9nNVOCGgbjdVqS","level":1,"time":"2020-01-30T10:29:33+01:00","remoteAddr":"111.222.333.444","user":"######","app":"no app in context","method":"POST","url":"/index.php/apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/1922872674/c/198/dq44hdvv/xhr_send?t=1580376572764","message":"Deprecated event type for \\OCP\\Files::preWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}
{"reqId":"zeHZfi9nNVOCGgbjdVqS","level":1,"time":"2020-01-30T10:29:33+01:00","remoteAddr":"111.222.333.444","user":"######","app":"no app in context","method":"POST","url":"/index.php/apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/1922872674/c/198/dq44hdvv/xhr_send?t=1580376572764","message":"Deprecated event type for \\OCP\\Files::postWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}
{"reqId":"zeHZfi9nNVOCGgbjdVqS","level":1,"time":"2020-01-30T10:29:33+01:00","remoteAddr":"111.222.333.444","user":"######","app":"no app in context","method":"POST","url":"/index.php/apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/1922872674/c/198/dq44hdvv/xhr_send?t=1580376572764","message":"Deprecated event type for \\OCP\\Files::preWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}
{"reqId":"zeHZfi9nNVOCGgbjdVqS","level":1,"time":"2020-01-30T10:29:33+01:00","remoteAddr":"111.222.333.444","user":"######","app":"no app in context","method":"POST","url":"/index.php/apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/1922872674/c/198/dq44hdvv/xhr_send?t=1580376572764","message":"Deprecated event type for \\OCP\\Files::preCreate: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}
{"reqId":"zeHZfi9nNVOCGgbjdVqS","level":1,"time":"2020-01-30T10:29:33+01:00","remoteAddr":"111.222.333.444","user":"######","app":"no app in context","method":"POST","url":"/index.php/apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/1922872674/c/198/dq44hdvv/xhr_send?t=1580376572764","message":"Deprecated event type for \\OCP\\Files::postWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}
{"reqId":"zeHZfi9nNVOCGgbjdVqS","level":1,"time":"2020-01-30T10:29:33+01:00","remoteAddr":"111.222.333.444","user":"######","app":"no app in context","method":"POST","url":"/index.php/apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/1922872674/c/198/dq44hdvv/xhr_send?t=1580376572764","message":"Deprecated event type for \\OCP\\Files::postCreate: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}
{"reqId":"zeHZfi9nNVOCGgbjdVqS","level":1,"time":"2020-01-30T10:29:33+01:00","remoteAddr":"111.222.333.444","user":"######","app":"no app in context","method":"POST","url":"/index.php/apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/1922872674/c/198/dq44hdvv/xhr_send?t=1580376572764","message":"Deprecated event type for \\OCP\\Files::preWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}
{"reqId":"zeHZfi9nNVOCGgbjdVqS","level":1,"time":"2020-01-30T10:29:33+01:00","remoteAddr":"111.222.333.444","user":"######","app":"no app in context","method":"POST","url":"/index.php/apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/1922872674/c/198/dq44hdvv/xhr_send?t=1580376572764","message":"Deprecated event type for \\OCP\\Files::postWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}
```

I must have missed something....

nextcloud 18.0.0
php 7.3
debian linux 9
Linux 4.9.0-11-amd64 on x86_64

**Comment by lenni-web** [comment] 2020-01-31 10:53
"Nextcloud 18 OnlyOffice is loading forever" -> I had the same problem, and for me it seems that is has something to do with php Caching (recommended for using with Nextcloud) ... when I deactivated the Caching everything works fine

**Comment by pieter-groeneweg** [comment] 2020-02-06 08:29
I can confirm.
Disabling the caching in config.php made the document open.
Using APCU 
'memcache.local' => '\OC\Memcache\APCu',

Though it takes some while to open. So I wouldn't say 'every thing works fine'.

re-enabling the memcache reverts to a non loading document...

**Comment by sinni800** [comment] 2020-02-07 20:34
For me the endless loading is accompanied with requests to 

https://my.domain/apps/documentserver_community/3rdparty/onlyoffice/documentserver/doc/4222984543/c/info?t=1581107586475

returning 404. It just keeps doing that until it stops trying and says "the document can be viewed"... But that's not possible either

**Comment by manojknaikade** [comment] 2020-02-14 10:00
> I can confirm.
> Disabling the caching in config.php made the document open.
> Using APCU
> 'memcache.local' => '\OC\Memcache\APCu',
> 
> Though it takes some while to open. So I wouldn't say 'every thing works fine'.
> 
> re-enabling the memcache reverts to a non loading document...

I can also confirm the same!
Is there any other way you could resolve the problem?

**Comment by manojknaikade** [comment] 2020-02-15 18:00
I was able to solve the problem by adding Redis for distributed cache

config.php looks like this now

```
 'memcache.local' => '\\OC\Memcache\APCu',
'memcache.distributed' => '\\OC\Memcache\Redis',
'memcache.locking' => '\\OC\Memcache\Redis',
'redis' => [
     'host' => '127.0.0.1 ::1',
     'port' => 6379,
],
```

**Comment by geiger-engineering** [comment] 2020-03-17 09:09
Just FYI, when using memcache.local with array cache ('memcache.local' => '\\OC\\Memcache\\ArrayCache'), the document will also keep loading forever.

**Comment by pieter-groeneweg** [comment] 2020-03-27 19:25
I can confirm, installing, and enabling "redis" works.
use these instructions. https://guides.wp-bullet.com/how-to-configure-redis-to-use-unix-socket-speed-boost/

**Comment by sturze** [comment] 2020-04-16 09:19
me too... my hoster seems not to provide redis
it only works for me when i disable local memcache... somebody any news/workarround?

**Comment by PlanetDyna** [comment] 2020-05-12 15:40
Up!

Any news?

**Comment by alexzand** [comment] 2020-05-13 23:54
Can confirm this. OnlyOffice is loading forever if you have the line
`'memcache.local' => '\OC\Memcache\ArrayCache',`
in your config.php

Removing this fixes the problem of OnlyOffice not loading but is not recommended.

Any other fix in sight rather than not using ArrayCache?

**Comment by ahlooii** [comment] 2020-05-20 00:32
Actually what is causing these issues, If it's simply the memcache, wouldn't that simply already be tested by nextcloud before pushing out Nextcloud 18(Hub) ? As memcache configuration are also stated in Nextcloud's Handbook for installing and configuring, so why it's not optimized for their default configuration? 

Hope it get fixes soon.

**Comment by neiion** [comment] 2020-06-28 16:18
Hi
Just wanted to post a solution that worked for me on this. i am running nextcloud via apache2 reverse proxy. i had trouble with the onlyoffice loading page timing out and going nowhere . i tried the memcache fix above but had no success. what fixed the issue for me was to add the following in my virtualhost config.

ProxyPreserveHost On

hopefully someone finds my fix useful

**Comment by dominikjur** [comment] 2020-07-02 14:16
Is there already a solution to the problem? Deactivating memcache permanently is probably not the best solution.

**Comment by Emporea** [comment] 2020-08-13 20:06
Any Updates? I am still facing this issue and don't want to disable memcache as a workaround.

**Comment by sebastiansterk** [comment] 2020-08-24 10:16
I have the exact same problem. I have redis enabled and the problem can be fixed by disabling redis and enable   'memcache.local' => '\\OC\\Memcache\\APCu',

Guess there is a general caching issue.

**Comment by Emporea** [comment] 2020-08-24 12:53
Yeah but this only seems to be a workaround and maybe slows down my setup?

**Comment by mayiagator** [comment] 2020-10-16 03:13
Hi. Posting my solution on similar case. I am running nextcloud 19 on a Centos 8 VM with Apache behind an nginx proxy for ssl upstream. I was having the same issue of endless loading when opening a file with onlyoffice. Changing SELINUX settings to  permissive and rebooting solved the issue for me.

**Comment by joskapista44** [comment] 2022-08-08 05:46
> Hi Just wanted to post a solution that worked for me on this. i am running nextcloud via apache2 reverse proxy. i had trouble with the onlyoffice loading page timing out and going nowhere . i tried the memcache fix above but had no success. what fixed the issue for me was to add the following in my virtualhost config.
> 
> ProxyPreserveHost On
> 
> hopefully someone finds my fix useful

Hi, could you please explain how did you do this exactly? Thank you

**Comment by chadek** [comment] 2024-07-12 11:32
Latest version work for Nextcloud 29

**Closed** 2024-07-12 11:31 UTC
Labels: bug
